CREATE TABLE IF NOT EXISTS WALLET_NONCES (
    ID VARCHAR(255) PRIMARY KEY,
    WALLET_ADDRESS VARCHAR(255) NOT NULL,
    NONCE VARCHAR(255) NOT NULL,
    CREATED_AT BIGINT,
    EXPIRES_AT BIGINT,
    USED BOOLEAN,
    USED_AT BIGINT
);

CREATE TABLE IF NOT EXISTS WALLET_CONNECTIONS (
    ID VARCHAR(255) PRIMARY KEY,
    ACCOUNT_ID VARCHAR(255) NOT NULL,
    WALLET_ADDRESS VARCHAR(255) NOT NULL,
    CHAIN VARCHAR(50),
    CHAIN_ID BIGINT,
    STATUS VARCHAR(50),
    CONNECTED_AT BIGINT,
    LAST_ACTIVE_AT BIGINT,
    IS_PRIMARY BOOLEAN,
    LABEL VARCHAR(255)
);
